name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    run-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to root
        run: |
          mkdir -p docs
          cp -r frontend/pages/* docs/

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

        
